name: release
on:
  release:
    types: [published]
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - uses: Swatinem/rust-cache@v2
    - name: Publish crates
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        ./scripts/publish.sh "${{ github.ref_name }}"